export const mockDfaData = [
  {
    project_id: "PRJ-BAN-001",
    form_id: "FRM-BAN-001",
    state: "BANADIR",
    regions: [
      {
        region: "Banadir",
        districts: [
          {
            district: "Abdi Aziz",
            dfa_cod: "DFA-BAN-001",
            campaign_days: [
              {
                campaign_day: "2024-06-01",
                no_of_team_assigned: 6,
                no_of_team_participated: 6,
                settlement_type: "Urban",
                no_of_dfa_assigned: 6,
                no_of_dfa_participated: 5,
                vacinated_0_11_zero_occurence: 200,
                vacinated_12_59_zero_occurence: 100,
                vacinated_0_11_multiple_occurence: 300,
                vacinated_12_59_multiple_occurence: 300,
                opv_received_total: 50,
                opv_usedemp_total: 40,
                // doses_Per_Vial: 20,
                revisited_unvaccinated_not_available: 4,
                revisited_unvaccinated_refusals: 2,
                revisited_unvaccinated_total: 6,
                number_of_houses_visited: 220,
                data_summary_id: 1001,
                created_at: "2024-06-01",
                updated_at: "2024-06-02"
              },
              {
                campaign_day: "2024-06-02",
                no_of_team_assigned: 6,
                no_of_team_participated: 6,
                settlement_type: "Urban",
                no_of_dfa_assigned: 6,
                no_of_dfa_participated: 5,
                vacinated_0_11_zero_occurence: 200,
                vacinated_12_59_zero_occurence: 100,
                vacinated_0_11_multiple_occurence: 300,
                vacinated_12_59_multiple_occurence: 400,
                opv_received_total: 50,
                opv_usedemp_total: 45,
                // doses_Per_Vial: 20,
                revisited_unvaccinated_not_available: 4,
                revisited_unvaccinated_refusals: 2,
                revisited_unvaccinated_total: 6,
                number_of_houses_visited: 220,
                data_summary_id: 1002,
                created_at: "2024-06-02",
                updated_at: "2024-06-03"
              }
            ]
          },
          {
            district: "BONDERE",
            dfa_cod: "DFA-BAN-002",
            campaign_days: [
              {
                campaign_day: "2024-06-01",
                no_of_team_assigned: 10,
                no_of_team_participated: 9,
                settlement_type: "Urban",
                no_of_dfa_assigned: 6,
                no_of_dfa_participated: 5,
                vacinated_0_11_zero_occurence: 100,
                vacinated_12_59_zero_occurence: 100,
                vacinated_0_11_multiple_occurence: 200,
                vacinated_12_59_multiple_occurence: 200,
                opv_received_total: 40,
                opv_usedemp_total: 30,
                // doses_Per_Vial: 20,
                revisited_unvaccinated_not_available: 4,
                revisited_unvaccinated_refusals: 2,
                revisited_unvaccinated_total: 6,
                number_of_houses_visited: 220,
                data_summary_id: 1003,
                created_at: "2024-06-01",
                updated_at: "2024-06-02"
              },
              {
                campaign_day: "2024-06-02",
                no_of_team_assigned: 10,
                no_of_team_participated: 10,
                settlement_type: "Urban",
                no_of_dfa_assigned: 6,
                no_of_dfa_participated: 5,
                vacinated_0_11_zero_occurence: 150,
                vacinated_12_59_zero_occurence: 100,
                vacinated_0_11_multiple_occurence: 200,
                vacinated_12_59_multiple_occurence: 200,
                opv_received_total: 35,
                opv_usedemp_total: 35,
                // doses_Per_Vial: 20,
                revisited_unvaccinated_not_available: 4,
                revisited_unvaccinated_refusals: 2,
                revisited_unvaccinated_total: 6,
                number_of_houses_visited: 220,
                data_summary_id: 1004,
                created_at: "2024-06-02",
                updated_at: "2024-06-03"
              }
            ]
          },
          {
            district: "Dayniile",
            dfa_cod: "DFA-BAN-003",
            campaign_days: [
              {
                campaign_day: "2024-06-01",
                no_of_team_assigned: 29,
                no_of_team_participated: 28,
                settlement_type: "Urban",
                no_of_dfa_assigned: 6,
                no_of_dfa_participated: 5,
                vacinated_0_11_zero_occurence: 200,
                vacinated_12_59_zero_occurence: 100,
                vacinated_0_11_multiple_occurence: 300,
                vacinated_12_59_multiple_occurence: 250,
                opv_received_total: 45,
                opv_usedemp_total: 43,
                // doses_Per_Vial: 20,
                revisited_unvaccinated_not_available: 4,
                revisited_unvaccinated_refusals: 2,
                revisited_unvaccinated_total: 6,
                number_of_houses_visited: 220,
                data_summary_id: 1005,
                created_at: "2024-06-02",
                updated_at: "2024-06-03"
              },
              {
                campaign_day: "2024-06-02",
                no_of_team_assigned: 29,
                no_of_team_participated: 29,
                settlement_type: "Urban",
                no_of_dfa_assigned: 6,
                no_of_dfa_participated: 5,
                vacinated_0_11_zero_occurence: 100,
                vacinated_12_59_zero_occurence: 100,
                vacinated_0_11_multiple_occurence: 200,
                vacinated_12_59_multiple_occurence: 300,
                opv_received_total: 40,
                opv_usedemp_total: 35,
                // doses_Per_Vial: 20,
                revisited_unvaccinated_not_available: 4,
                revisited_unvaccinated_refusals: 2,
                revisited_unvaccinated_total: 6,
                number_of_houses_visited: 220,
                data_summary_id: 1006,
                created_at: "2024-06-02",
                updated_at: "2024-06-03"
              }
            ]
          },
          {
            district: "DHARKENLEY",
            dfa_cod: "DFA-BAN-004",
            campaign_days: [
              {
                campaign_day: "2024-06-01",
                no_of_team_assigned: 16,
                no_of_team_participated: 17,
                settlement_type: "Urban",
                no_of_dfa_assigned: 6,
                no_of_dfa_participated: 5,
                vacinated_0_11_zero_occurence: 100,
                vacinated_12_59_zero_occurence: 100,
                vacinated_0_11_multiple_occurence: 200,
                vacinated_12_59_multiple_occurence: 200,
                opv_received_total: 30,
                opv_usedemp_total: 25,
                // doses_Per_Vial: 20,
                revisited_unvaccinated_not_available: 4,
                revisited_unvaccinated_refusals: 2,
                revisited_unvaccinated_total: 6,
                number_of_houses_visited: 220,
                data_summary_id: 1007,
                created_at: "2024-06-02",
                updated_at: "2024-06-03"
              },
              {
                campaign_day: "2024-06-02",
                no_of_team_assigned: 16,
                no_of_team_participated: 16,
                settlement_type: "Urban",
                no_of_dfa_assigned: 6,
                no_of_dfa_participated: 5,
                vacinated_0_11_zero_occurence: 200,
                vacinated_12_59_zero_occurence: 100,
                vacinated_0_11_multiple_occurence: 200,
                vacinated_12_59_multiple_occurence: 300,
                opv_received_total: 40,
                opv_usedemp_total: 40,
                // doses_Per_Vial: 20,
                revisited_unvaccinated_not_available: 4,
                revisited_unvaccinated_refusals: 2,
                revisited_unvaccinated_total: 6,
                number_of_houses_visited: 220,
                data_summary_id: 1008,
                created_at: "2024-06-02",
                updated_at: "2024-06-03"
              }
            ]
          },
          {
            district: "Hamar Jabjab",
            dfa_cod: "DFA-BAN-005",
            campaign_days: [
              {
                campaign_day: "2024-06-01",
                no_of_team_assigned: 9,
                no_of_team_participated: 9,
                settlement_type: "Urban",
                no_of_dfa_assigned: 6,
                no_of_dfa_participated: 5,
                vacinated_0_11_zero_occurence: 200,
                vacinated_12_59_zero_occurence: 200,
                vacinated_0_11_multiple_occurence: 300,
                vacinated_12_59_multiple_occurence: 300,
                opv_received_total: 60,
                opv_usedemp_total: 50,
                // doses_Per_Vial: 20,
                revisited_unvaccinated_not_available: 4,
                revisited_unvaccinated_refusals: 2,
                revisited_unvaccinated_total: 6,
                number_of_houses_visited: 220,
                data_summary_id: 1009,
                created_at: "2024-06-02",
                updated_at: "2024-06-03"
              },
              {
                campaign_day: "2024-06-02",
                no_of_team_assigned: 9,
                no_of_team_participated: 9,
                settlement_type: "Urban",
                no_of_dfa_assigned: 6,
                no_of_dfa_participated: 5,
                vacinated_0_11_zero_occurence: 100,
                vacinated_12_59_zero_occurence: 100,
                vacinated_0_11_multiple_occurence: 300,
                vacinated_12_59_multiple_occurence: 400,
                opv_received_total: 50,
                opv_usedemp_total: 45,
                // doses_Per_Vial: 20,
                revisited_unvaccinated_not_available: 4,
                revisited_unvaccinated_refusals: 2,
                revisited_unvaccinated_total: 6,
                number_of_houses_visited: 220,
                data_summary_id: 1010,
                created_at: "2024-06-02",
                updated_at: "2024-06-03"
              }
            ]
          },
          {
            district: "Hamarwene",
            dfa_cod: "DFA-BAN-006",
            campaign_days: [
              {
                campaign_day: "2024-06-01",
                no_of_team_assigned: 10,
                no_of_team_participated: 12,
                settlement_type: "Urban",
                no_of_dfa_assigned: 6,
                no_of_dfa_participated: 5,
                vacinated_0_11_zero_occurence: 250,
                vacinated_12_59_zero_occurence: 200,
                vacinated_0_11_multiple_occurence: 300,
                vacinated_12_59_multiple_occurence: 300,
                opv_received_total: 45,
                opv_usedemp_total: 45,
                // doses_Per_Vial: 20,
                revisited_unvaccinated_not_available: 4,
                revisited_unvaccinated_refusals: 2,
                revisited_unvaccinated_total: 6,
                number_of_houses_visited: 220,
                data_summary_id: 1011,
                created_at: "2024-06-01",
                updated_at: "2024-06-02"
              },
              {
                campaign_day: "2024-06-02",
                no_of_team_assigned: 10,
                no_of_team_participated: 10,
                settlement_type: "Urban",
                no_of_dfa_assigned: 6,
                no_of_dfa_participated: 5,
                vacinated_0_11_zero_occurence: 200,
                vacinated_12_59_zero_occurence: 100,
                vacinated_0_11_multiple_occurence: 300,
                vacinated_12_59_multiple_occurence: 400,
                opv_received_total: 50,
                opv_usedemp_total: 50,
                // doses_Per_Vial: 20,
                revisited_unvaccinated_not_available: 4,
                revisited_unvaccinated_refusals: 2,
                revisited_unvaccinated_total: 6,
                number_of_houses_visited: 220,
                data_summary_id: 1012,
                created_at: "2024-06-02",
                updated_at: "2024-06-03"
              }
            ]
          },
          {
            district: "Heliwa",
            dfa_cod: "DFA-BAN-007",
            campaign_days: [
              {
                campaign_day: "2024-06-01",
                no_of_team_assigned: 22,
                no_of_team_participated: 24,
                settlement_type: "Urban",
                no_of_dfa_assigned: 6,
                no_of_dfa_participated: 5,
                vacinated_0_11_zero_occurence: 100,
                vacinated_12_59_zero_occurence: 100,
                vacinated_0_11_multiple_occurence: 200,
                vacinated_12_59_multiple_occurence: 300,
                opv_received_total: 40,
                opv_usedemp_total: 35,
                // doses_Per_Vial: 20,
                revisited_unvaccinated_not_available: 4,
                revisited_unvaccinated_refusals: 2,
                revisited_unvaccinated_total: 6,
                number_of_houses_visited: 220,
                data_summary_id: 1013,
                created_at: "2024-06-01",
                updated_at: "2024-06-02"
              },
              {
                campaign_day: "2024-06-02",
                no_of_team_assigned: 22,
                no_of_team_participated: 22,
                settlement_type: "Urban",
                no_of_dfa_assigned: 6,
                no_of_dfa_participated: 5,
                vacinated_0_11_zero_occurence: 200,
                vacinated_12_59_zero_occurence: 100,
                vacinated_0_11_multiple_occurence: 300,
                vacinated_12_59_multiple_occurence: 400,
                opv_received_total: 60,
                opv_usedemp_total: 55,
                // doses_Per_Vial: 20,
                revisited_unvaccinated_not_available: 4,
                revisited_unvaccinated_refusals: 2,
                revisited_unvaccinated_total: 6,
                number_of_houses_visited: 220,
                data_summary_id: 1014,
                created_at: "2024-06-02",
                updated_at: "2024-06-03"
              }
            ]
          },
          {
            district: "Hodan",
            dfa_cod: "DFA-BAN-008",
            campaign_days: [
              {
                campaign_day: "2024-06-01",
                no_of_team_assigned: 24,
                no_of_team_participated: 24,
                settlement_type: "Urban",
                no_of_dfa_assigned: 6,
                no_of_dfa_participated: 5,
                vacinated_0_11_zero_occurence: 100,
                vacinated_12_59_zero_occurence: 100,
                vacinated_0_11_multiple_occurence: 300,
                vacinated_12_59_multiple_occurence: 300,
                opv_received_total: 45,
                opv_usedemp_total: 40,
                // doses_Per_Vial: 20,
                revisited_unvaccinated_not_available: 4,
                revisited_unvaccinated_refusals: 2,
                revisited_unvaccinated_total: 6,
                number_of_houses_visited: 220,
                data_summary_id: 1015,
                created_at: "2024-06-02",
                updated_at: "2024-06-03"
              },
              {
                campaign_day: "2024-06-02",
                no_of_team_assigned: 24,
                no_of_team_participated: 24,
                settlement_type: "Urban",
                no_of_dfa_assigned: 6,
                no_of_dfa_participated: 5,
                vacinated_0_11_zero_occurence: 100,
                vacinated_12_59_zero_occurence: 50,
                vacinated_0_11_multiple_occurence: 300,
                vacinated_12_59_multiple_occurence: 250,
                opv_received_total: 35,
                opv_usedemp_total: 35,
                // doses_Per_Vial: 20,
                revisited_unvaccinated_not_available: 4,
                revisited_unvaccinated_refusals: 2,
                revisited_unvaccinated_total: 6,
                number_of_houses_visited: 220,
                data_summary_id: 1016,
                created_at: "2024-06-02",
                updated_at: "2024-06-03"
              }
            ]
          },
          {
            district: "Howlwadaag",
            dfa_cod: "DFA-BAN-009",
            campaign_days: [
              {
                campaign_day: "2024-06-01",
                no_of_team_assigned: 11,
                no_of_team_participated: 10,
                settlement_type: "Urban",
                no_of_dfa_assigned: 6,
                no_of_dfa_participated: 5,
                vacinated_0_11_zero_occurence: 200,
                vacinated_12_59_zero_occurence: 100,
                vacinated_0_11_multiple_occurence: 400,
                vacinated_12_59_multiple_occurence: 400,
                opv_received_total: 55,
                opv_usedemp_total: 55,
                // doses_Per_Vial: 20,
                revisited_unvaccinated_not_available: 4,
                revisited_unvaccinated_refusals: 2,
                revisited_unvaccinated_total: 6,
                number_of_houses_visited: 220,
                data_summary_id: 1017,
                created_at: "2024-06-02",
                updated_at: "2024-06-03"
              },
              {
                campaign_day: "2024-06-02",
                no_of_team_assigned: 11,
                no_of_team_participated: 11,
                settlement_type: "Urban",
                no_of_dfa_assigned: 6,
                no_of_dfa_participated: 5,
                vacinated_0_11_zero_occurence: 100,
                vacinated_12_59_zero_occurence: 100,
                vacinated_0_11_multiple_occurence: 300,
                vacinated_12_59_multiple_occurence: 300,
                opv_received_total: 40,
                opv_usedemp_total: 40,
                // doses_Per_Vial: 20,
                revisited_unvaccinated_not_available: 4,
                revisited_unvaccinated_refusals: 2,
                revisited_unvaccinated_total: 6,
                number_of_houses_visited: 220,
                data_summary_id: 1018,
                created_at: "2024-06-02",
                updated_at: "2024-06-03"
              }
            ]
          },
          {
            district: "KAHDA",
            dfa_cod: "DFA-BAN-010",
            campaign_days: [
              {
                campaign_day: "2024-06-01",
                no_of_team_assigned: 24,
                no_of_team_participated: 25,
                settlement_type: "Urban",
                no_of_dfa_assigned: 6,
                no_of_dfa_participated: 5,
                vacinated_0_11_zero_occurence: 250,
                vacinated_12_59_zero_occurence: 150,
                vacinated_0_11_multiple_occurence: 300,
                vacinated_12_59_multiple_occurence: 300,
                opv_received_total: 50,
                opv_usedemp_total: 35,
                // doses_Per_Vial: 20,
                revisited_unvaccinated_not_available: 4,
                revisited_unvaccinated_refusals: 2,
                revisited_unvaccinated_total: 6,
                number_of_houses_visited: 220,
                data_summary_id: 1019,
                created_at: "2024-06-02",
                updated_at: "2024-06-03"
              },
              {
                campaign_day: "2024-06-02",
                no_of_team_assigned: 24,
                no_of_team_participated: 24,
                settlement_type: "Urban",
                no_of_dfa_assigned: 6,
                no_of_dfa_participated: 5,
                vacinated_0_11_zero_occurence: 200,
                vacinated_12_59_zero_occurence: 200,
                vacinated_0_11_multiple_occurence: 300,
                vacinated_12_59_multiple_occurence: 300,
                opv_received_total: 50,
                opv_usedemp_total: 45,
                // doses_Per_Vial: 20,
                revisited_unvaccinated_not_available: 4,
                revisited_unvaccinated_refusals: 2,
                revisited_unvaccinated_total: 6,
                number_of_houses_visited: 220,
                data_summary_id: 1020,
                created_at: "2024-06-02",
                updated_at: "2024-06-03"
              }
            ]
          }
        ]
      }
    ]
  },
  {
    project_id: "PRJ-GAL-001",
    form_id: "FRM-GAL-001",
    state: "GALMUDUG",
    regions: [
      {
        region: "GALGADUD",
        districts: [
          {
            district: "ABUDWAK",
            dfa_cod: "DFA-GAL-001",
            campaign_days: [
              {
                campaign_day: "2024-06-01",
                no_of_team_assigned: 24,
                no_of_team_participated: 24,
                settlement_type: "Urban",
                no_of_dfa_assigned: 6,
                no_of_dfa_participated: 5,
                vacinated_0_11_zero_occurence: 50,
                vacinated_12_59_zero_occurence: 50,
                vacinated_0_11_multiple_occurence: 100,
                vacinated_12_59_multiple_occurence: 100,
                opv_received_total: 20,
                opv_usedemp_total: 15,
                // doses_Per_Vial: 20,
                revisited_unvaccinated_not_available: 4,
                revisited_unvaccinated_refusals: 2,
                revisited_unvaccinated_total: 6,
                number_of_houses_visited: 220,
                data_summary_id: 1021,
                created_at: "2024-06-01",
                updated_at: "2024-06-02"
              },
              {
                campaign_day: "2024-06-02",
                no_of_team_assigned: 24,
                no_of_team_participated: 24,
                settlement_type: "Urban",
                no_of_dfa_assigned: 6,
                no_of_dfa_participated: 5,
                vacinated_0_11_zero_occurence: 100,
                vacinated_12_59_zero_occurence: 100,
                vacinated_0_11_multiple_occurence: 200,
                vacinated_12_59_multiple_occurence: 200,
                opv_received_total: 30,
                opv_usedemp_total: 30,
                // doses_Per_Vial: 20,
                revisited_unvaccinated_not_available: 4,
                revisited_unvaccinated_refusals: 2,
                revisited_unvaccinated_total: 6,
                number_of_houses_visited: 220,
                data_summary_id: 1022,
                created_at: "2024-06-02",
                updated_at: "2024-06-03"
              }
            ]
          },
          {
            district: "ADADO",
            dfa_cod: "DFA-GAL-002",
            campaign_days: [
              {
                campaign_day: "2024-06-01",
                no_of_team_assigned: 22,
                no_of_team_participated: 22,
                settlement_type: "Urban",
                no_of_dfa_assigned: 6,
                no_of_dfa_participated: 5,
                vacinated_0_11_zero_occurence: 100,
                vacinated_12_59_zero_occurence: 100,
                vacinated_0_11_multiple_occurence: 150,
                vacinated_12_59_multiple_occurence: 250,
                opv_received_total: 30,
                opv_usedemp_total: 20,
                // doses_Per_Vial: 20,
                revisited_unvaccinated_not_available: 4,
                revisited_unvaccinated_refusals: 2,
                revisited_unvaccinated_total: 6,
                number_of_houses_visited: 220,
                data_summary_id: 1023,
                created_at: "2024-06-01",
                updated_at: "2024-06-02"
              },
              {
                campaign_day: "2024-06-02",
                no_of_team_assigned: 22,
                no_of_team_participated: 22,
                settlement_type: "Urban",
                no_of_dfa_assigned: 6,
                no_of_dfa_participated: 5,
                vacinated_0_11_zero_occurence: 100,
                vacinated_12_59_zero_occurence: 100,
                vacinated_0_11_multiple_occurence: 250,
                vacinated_12_59_multiple_occurence: 250,
                opv_received_total: 35,
                opv_usedemp_total: 20,
                // doses_Per_Vial: 20,
                revisited_unvaccinated_not_available: 4,
                revisited_unvaccinated_refusals: 2,
                revisited_unvaccinated_total: 6,
                number_of_houses_visited: 220,
                data_summary_id: 1024,
                created_at: "2024-06-02",
                updated_at: "2024-06-03"
              }
            ]
          },
          {
            district: "BALANBALLE",
            dfa_cod: "DFA-GAL-003",
            campaign_days: [
              {
                campaign_day: "2024-06-01",
                no_of_team_assigned: 11,
                no_of_team_participated: 12,
                settlement_type: "Urban",
                no_of_dfa_assigned: 6,
                no_of_dfa_participated: 5,
                vacinated_0_11_zero_occurence: 100,
                vacinated_12_59_zero_occurence: 50,
                vacinated_0_11_multiple_occurence: 200,
                vacinated_12_59_multiple_occurence: 200,
                opv_received_total: 30,
                opv_usedemp_total: 23,
                // doses_Per_Vial: 20,
                revisited_unvaccinated_not_available: 4,
                revisited_unvaccinated_refusals: 2,
                revisited_unvaccinated_total: 6,
                number_of_houses_visited: 220,
                data_summary_id: 1025,
                created_at: "2024-06-01",
                updated_at: "2024-06-02"
              },
              {
                campaign_day: "2024-06-02",
                no_of_team_assigned: 11,
                no_of_team_participated: 11,
                settlement_type: "Urban",
                no_of_dfa_assigned: 6,
                no_of_dfa_participated: 5,
                vacinated_0_11_zero_occurence: 100,
                vacinated_12_59_zero_occurence: 100,
                vacinated_0_11_multiple_occurence: 200,
                vacinated_12_59_multiple_occurence: 200,
                opv_received_total: 30,
                opv_usedemp_total: 30,
                // doses_Per_Vial: 20,
                revisited_unvaccinated_not_available: 4,
                revisited_unvaccinated_refusals: 2,
                revisited_unvaccinated_total: 6,
                number_of_houses_visited: 220,
                data_summary_id: 1026,
                created_at: "2024-06-02",
                updated_at: "2024-06-03"
              }
            ]
          },
          {
            district: "ELDHER",
            dfa_cod: "DFA-GAL-004",
            campaign_days: [
              {
                campaign_day: "2024-06-01",
                no_of_team_assigned: 21,
                no_of_team_participated: 18,
                settlement_type: "Urban",
                no_of_dfa_assigned: 6,
                no_of_dfa_participated: 5,
                vacinated_0_11_zero_occurence: 100,
                vacinated_12_59_zero_occurence: 100,
                vacinated_0_11_multiple_occurence: 100,
                vacinated_12_59_multiple_occurence: 100,
                opv_received_total: 20,
                opv_usedemp_total: 20,
                // doses_Per_Vial: 20,
                revisited_unvaccinated_not_available: 4,
                revisited_unvaccinated_refusals: 2,
                revisited_unvaccinated_total: 6,
                number_of_houses_visited: 220,
                data_summary_id: 1027,
                created_at: "2024-06-01",
                updated_at: "2024-06-02"
              },
              {
                campaign_day: "2024-06-02",
                no_of_team_assigned: 21,
                no_of_team_participated: 21,
                settlement_type: "Urban",
                no_of_dfa_assigned: 6,
                no_of_dfa_participated: 5,
                vacinated_0_11_zero_occurence: 100,
                vacinated_12_59_zero_occurence: 100,
                vacinated_0_11_multiple_occurence: 250,
                vacinated_12_59_multiple_occurence: 250,
                opv_received_total: 35,
                opv_usedemp_total: 30,
                // doses_Per_Vial: 20,
                revisited_unvaccinated_not_available: 4,
                revisited_unvaccinated_refusals: 2,
                revisited_unvaccinated_total: 6,
                number_of_houses_visited: 220,
                data_summary_id: 1028,
                created_at: "2024-06-02",
                updated_at: "2024-06-03"
              }
            ]
          }
        ]
      },
      {
        region: "SOUTH MUDUG",
        districts: [
          {
            district: "HARARDHERE",
            dfa_cod: "DFA-SMU-001",
            campaign_days: [
              {
                campaign_day: "2024-06-01",
                no_of_team_assigned: 11,
                no_of_team_participated: 0,
                settlement_type: "Urban",
                no_of_dfa_assigned: 6,
                no_of_dfa_participated: 5,
                vacinated_0_11_zero_occurence: 120,
                vacinated_12_59_zero_occurence: 130,
                vacinated_0_11_multiple_occurence: 250,
                vacinated_12_59_multiple_occurence: 350,
                opv_received_total: 45,
                opv_usedemp_total: 42,
                // doses_Per_Vial: 20,
                revisited_unvaccinated_not_available: 4,
                revisited_unvaccinated_refusals: 2,
                revisited_unvaccinated_total: 6,
                number_of_houses_visited: 220,
                data_summary_id: 1029,
                created_at: "2024-06-01",
                updated_at: "2024-06-02"
              },
              {
                campaign_day: "2024-06-02",
                no_of_team_assigned: 11,
                no_of_team_participated: 11,
                settlement_type: "Urban",
                no_of_dfa_assigned: 6,
                no_of_dfa_participated: 5,
                vacinated_0_11_zero_occurence: 150,
                vacinated_12_59_zero_occurence: 150,
                vacinated_0_11_multiple_occurence: 250,
                vacinated_12_59_multiple_occurence: 250,
                opv_received_total: 40,
                opv_usedemp_total: 30,
                // doses_Per_Vial: 20,
                revisited_unvaccinated_not_available: 4,
                revisited_unvaccinated_refusals: 2,
                revisited_unvaccinated_total: 6,
                number_of_houses_visited: 220,
                data_summary_id: 1030,
                created_at: "2024-06-02",
                updated_at: "2024-06-03"
              }
            ]
          },
          {
            district: "HOBYO",
            dfa_cod: "DFA-SMU-002",
            campaign_days: [
              {
                campaign_day: "2024-06-01",
                no_of_team_assigned: 36,
                no_of_team_participated: 36,
                settlement_type: "Urban",
                no_of_dfa_assigned: 6,
                no_of_dfa_participated: 5,
                vacinated_0_11_zero_occurence: 100,
                vacinated_12_59_zero_occurence: 100,
                vacinated_0_11_multiple_occurence: 200,
                vacinated_12_59_multiple_occurence: 200,
                opv_received_total: 30,
                opv_usedemp_total: 30,
                // doses_Per_Vial: 20,
                revisited_unvaccinated_not_available: 4,
                revisited_unvaccinated_refusals: 2,
                revisited_unvaccinated_total: 6,
                number_of_houses_visited: 220,
                data_summary_id: 1031,
                created_at: "2024-06-01",
                updated_at: "2024-06-02"
              },
              {
                campaign_day: "2024-06-02",
                no_of_team_assigned: 36,
                no_of_team_participated: 36,
                settlement_type: "Urban",
                no_of_dfa_assigned: 6,
                no_of_dfa_participated: 5,
                vacinated_0_11_zero_occurence: 100,
                vacinated_12_59_zero_occurence: 100,
                vacinated_0_11_multiple_occurence: 200,
                vacinated_12_59_multiple_occurence: 200,
                opv_received_total: 30,
                opv_usedemp_total: 30,
                // doses_Per_Vial: 20,
                revisited_unvaccinated_not_available: 4,
                revisited_unvaccinated_refusals: 2,
                revisited_unvaccinated_total: 6,
                number_of_houses_visited: 220,
                data_summary_id: 1032,
                created_at: "2024-06-02",
                updated_at: "2024-06-03"
              }
            ]
          },
          {
            district: "SOUTH GALKAYO",
            dfa_cod: "DFA-SMU-003",
            campaign_days: [
              {
                campaign_day: "2024-06-01",
                no_of_team_assigned: 29,
                no_of_team_participated: 29,
                settlement_type: "Urban",
                no_of_dfa_assigned: 6,
                no_of_dfa_participated: 5,
                vacinated_0_11_zero_occurence: 50,
                vacinated_12_59_zero_occurence: 50,
                vacinated_0_11_multiple_occurence: 100,
                vacinated_12_59_multiple_occurence: 100,
                opv_received_total: 20,
                opv_usedemp_total: 15,
                // doses_Per_Vial: 20,
                revisited_unvaccinated_not_available: 4,
                revisited_unvaccinated_refusals: 2,
                revisited_unvaccinated_total: 6,
                number_of_houses_visited: 220,
                data_summary_id: 1033,
                created_at: "2024-06-01",
                updated_at: "2024-06-02"
              },
              {
                campaign_day: "2024-06-02",
                no_of_team_assigned: 29,
                no_of_team_participated: 29,
                settlement_type: "Urban",
                no_of_dfa_assigned: 6,
                no_of_dfa_participated: 5,
                vacinated_0_11_zero_occurence: 75,
                vacinated_12_59_zero_occurence: 75,
                vacinated_0_11_multiple_occurence: 250,
                vacinated_12_59_multiple_occurence: 250,
                opv_received_total: 30,
                opv_usedemp_total: 33,
                // doses_Per_Vial: 20,
                revisited_unvaccinated_not_available: 4,
                revisited_unvaccinated_refusals: 2,
                revisited_unvaccinated_total: 6,
                number_of_houses_visited: 220,
                data_summary_id: 1034,
                created_at: "2024-06-02",
                updated_at: "2024-06-03"
              }
            ]
          }
        ]
      }
    ]
  }
];